Repository owncloud/ocis-konnectd, pull requests merged in 2020-03, with the labels that each got.

#46 Add missing env-vars and cmd args to documentation
  docs/getting-started.md
Labels: documentation

#28 Don't create dummy index.html for webapp
  changelog/unreleased/disable-identifier.md
  docs/getting-started.md
  pkg/flagset/flagset.go
  pkg/service/v0/service.go
Labels: enhancement

#50 Fix tls-key flag
  pkg/flagset/flagset.go
Labels: bug

#52 integrate with current ocis config
  changelog/unreleased/new-ocis-config.md
  pkg/flagset/flagset.go
  pkg/service/v0/service.go
Labels: enhancement
